  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container-1/container-1:latest'
      - './'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container-1/container-1:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_COMPUTE_REGION
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
      - '--namespace'
      - 'container-1'
