  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container-1/container-1:latest'
      - './'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container-1/container-1:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "CLOUDSDK_COMPUTE_REGION=us-central1" >> $BASH_ENV
      echo "CLOUDSDK_COMPUTE_ZONE=us-central1-a" >> $BASH_ENV
      echo "CLOUDSDK_CONTAINER_CLUSTER=csci5409a3" >> $BASH_ENV
      gcloud container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER --region $CLOUDSDK_COMPUTE_REGION    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '$_CLUSTER_NAME'
      - '--region'
      - '$_COMPUTE_REGION'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
      - '--namespace'
      - 'container-1'
