apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage
spec:
  storageClassName: standard
  capacity:
    storage: 10
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: app-storage-claim
  gcePersistentDisk:
    pdName: gke-standard-cluster-default-pool-c44131dd-krh0
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10